[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mycolorpy"
version = "1.5.3"
authors = [
  { name="Binod Bhattarai", email="bbhattarai@ucmerced.edu" },
]
description = "A scientific visualization toolkit for generating dynamic color arrays from any colormap"
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
keywords = ["Color", "Hexcolor", "Colormap"]
dependencies = [
    "numpy>=1.21",
    "matplotlib>=3.4.0",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.urls]
Homepage = "https://github.com/binodbhttr/mycolorpy"

[tool.setuptools]
packages = ["mycolorpy"]